### ISSUE TITLE
AsChild scope command - validate as child type

### ISSUE THREAD

**Issue by kislovs** [bartoszlenar/Validot#24]
## Feature description

* Validating parent type as one of child type.
* Same feature in [FluentValidation](https://docs.fluentvalidation.net/en/latest/inheritance.html).

## Feature in action

``` csharp
// assume FirstChildType and SecondChildType both inherited from ParentType

Specification<FirstChildType> firstChildTypeSpecification = s => s;

Specification<SecondChildType> secondChildTypeSpecification = s => s;

Specification<ParentType> parentType = s => s
    .Rule(...) // executed for both "branches"
    .AsChild<FirstChildType>(firstChildTypeSpecification) // only if validated entity is actually FirstChildType
    .AsChild<SecondChildType>(secondChildTypeSpecification); // only if validated entity is actually SecondChildType

```

## Feature details

* New scope command: `AsChild<TChild>`.
* Works under hood as `AsModel` (?) + condition check.
* Should extend rules defined at parent level, not override.
* Should be executed after parent level rules (?).

## Discussion

* Maybe different naming to point exact purpose of this extension?
* Allow only (abstract) classes or interfaces as well?

**Comment by bartoszlenar** [comment]
Thank you, @kislovs, for your contribution. 

At first indeed it does look like it could be handled with the `AsType` and `AsChild` isn't necessary, but let me get back to this in a week time, after my vacations.

**Comment by bartoszlenar** [comment]
@kislovs I'm on the #3 at the moment and it looks like this one indeed could be achieved by a special version of `AsType`.

Anyway, I decided to postpone investigation for this one until #3 is fully completed and published in version 2.3 (coming very soon), because probably under the hood they could be the same piece of code. And I prefer going one step at the time.

**Comment by kislovs** [comment]
@bartoszlenar, I've subscribed for #3, want to see how you'll implement it and try to apply it to our source problem. :slightly_smiling_face:

**Comment by bartoszlenar** [comment]
As for this moment (#3 is merged, will be part of 2.3 very soon), `AsChild` could be implemented combining `AsConverted` and `WithCondition`.

``` csharp
.AsConverted(value => value as ChildType, childSpecification)
.WithCondition(value => value is ChildType)
```

`AsChild` will be part of the next release

**Comment by bartoszlenar** [comment]
The more I think about it the more I'm convinced that it should be called `AsType` (funny thing as originally `AsConverted` from #3 had been planned with this very name).

With `A -> B -> C` relationship, technically you could have `Specification<B>` and inside `AsType` with specifications for both `A` (always will be triggered, obviously) and `C` (triggered only if `B is C`). Therefore it would work similarly to `AsNullable` in the sense that if object isn't of a certain type, nothing happens.

**Comment by bartoszlenar** [comment]
@kislovs the feature is basically done (few more tests remains) and will be relased with the 2.4 version 1st of October.

quick summary:

- The final name of the command is `AsType`
- `s => s.AsType(anotherTypeSpecification)` will trigger `anotherTypeSpecifiction` if the validated value passes `is TAnotherType`, otherwise nothing happens (no error is recorded)
- `AsType` is a part of fluent api interface and therefore it's impossible to construct it with just `AsType<TargetType>`, because technically it has two generic parameters. You'll need to write the full version of `AsType<SourceType, TargetType>`, where `SourceType` is known to the compiler (from the current specification). The alternative is to use specifiction's constructor, like this:  `AsType(new Specification<TargetType>(s => s ...))`

**Comment by bartoszlenar** [comment]
Hey @kislovs ! :) 

It's merged: https://github.com/bartoszlenar/Validot/commit/c2d76b6232447ece0b8a349704a6088db9141b94
And 2.4.0 has already landed on the nuget registry.
